-- 0001.sql: CREATE TABLE user and ALTER TABLE article


CREATE TABLE user(
	pk INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id VARCHAR(30),
	username VARCHAR(30),
	hashed_password VARCHAR(128),
	date_joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	is_active TINYINT,
	is_staff TINYINT DEFAULT 0
) CHARSET UTF8 COLLATE utf8_general_ci;

ALTER TABLE article
	MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFY COLUMN last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	ALTER COLUMN is_active SET DEFAULT 1,
	ALTER COLUMN is_deleted SET DEFAULT 0;

ALTER TABLE article
	ADD FOREIGN KEY (author) REFERENCES user(pk) ON DELETE SET NULL;

